GET http://localhost:3000

### GET ALL Books
GET http://localhost:3000/books
Content-Type: application/json


### POST one book
POST http://localhost:3000/books
Content-Type: application/json

 {
    "title": "Naruto, Vol. 2: The Worst Client",
    "publishedAt": "2000-02-21T00:00:00.000Z",
    "editorialForm": "mangá",
    "content": "Action, Adventure",
    "isbn": "9781569319017",
    "price": 9.99
  }


### DELETE Books Bulk
DELETE http://localhost:3000/books/bulk
Content-Type: application/json

[9,1,11]

### Create Many Books Bulk
POST http://localhost:3000/books/bulk
Content-Type: application/json

[
  {
    "title": "Naruto, Vol. 1: Uzumaki Naruto",
    "publishedAt": "1999-09-21T00:00:00.000Z",
    "editorialForm": "mangá",
    "content": "Action, Adventure",
    "isbn": "9781569319000",
    "price": 9.99
  },
  {
    "title": "Naruto, Vol. 2: The Worst Client",
    "publishedAt": "2000-02-21T00:00:00.000Z",
    "editorialForm": "mangá",
    "content": "Action, Adventure",
    "isbn": "9781569319017",
    "price": 9.99
  },
  {
    "title": "Naruto, Vol. 3: For the Sake of Dreams...!!",
    "publishedAt": "2000-05-21T00:00:00.000Z",
    "editorialForm": "mangá",
    "content": "Action, Adventure",
    "isbn": "9781569319024",
    "price": 9.99
  },
  {
    "title": "Naruto, Vol. 4: The Hero's Bridge",
    "publishedAt": "2000-08-21T00:00:00.000Z",
    "editorialForm": "mangá",
    "content": "Action, Adventure",
    "isbn": "9781569319031",
    "price": 9.99
  },
  {
    "title": "Naruto, Vol. 5: The Challengers",
    "publishedAt": "2000-11-21T00:00:00.000Z",
    "editorialForm": "mangá",
    "content": "Action, Adventure",
    "isbn": "9781569319048",
    "price": 9.99
  },
  {
    "title": "Naruto, Vol. 6: Predator",
    "publishedAt": "2001-02-21T00:00:00.000Z",
    "editorialForm": "mangá",
    "content": "Action, Adventure",
    "isbn": "9781569319055",
    "price": 9
  }
]
