### AUTH Login
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "eroshi@aros.com",
  "password": "123456"
}


### create collection/page between user
POST http://localhost:3000/collection/page
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
    "currentStatusTrack": "lendo",
    "page":22,
    "contentId":3
}

### update collection between user
PATCH http://localhost:3000/collection/page
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
    "currentStatusTrack":"lendo",
    "page":285,
    "contentId":1
}

### get collection between user
GET http://localhost:3000/collection
Authorization: Bearer {{login.response.body.accessToken}}

### get search book in collection by name
GET http://localhost:3000/collection/search
Authorization: Bearer {{login.response.body.accessToken}}
