### AUTH Login
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "andre-carlos@Live.com",
  "password": "123456"
}


### create collection/page between user
POST http://localhost:3000/collection/page
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
    "currentStatusTrack": "reading",
    "page":8,
    "contentId":28
}

### update collection between user
PATCH http://localhost:3000/collection/page
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
    "currentStatusTrack":"lendo",
    "contentId":1
}

### get collection between user
GET http://localhost:3000/collection
Authorization: Bearer {{login.response.body.accessToken}}

### get search book in collection by name
GET http://localhost:3000/collection/search?q=
Authorization: Bearer {{login.response.body.accessToken}}


### GET REQUEST ALEXA
GET http://localhost:3000/collection/alexa/search?q=1%20piece%202&status=reading
Authorization: Bearer {{login.response.body.accessToken}}