### AUTH Login
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "kohado@aros.com",
  "password": "123456"
}

### create status content type
POST http://localhost:3000/status-contentype
Content-Type: application/json

{
  "name": [
    "lendo",
    "lido",
    "abandonado"
  ]
}

### create content type
POST http://localhost:3000/contenttype
Content-Type: application/json

{
    "name":"book",
    "statusType": {
      "id": 1
    }
}


### GET all content type
GET http://localhost:3000/contenttype
Content-Type: application/json

{
    "name":"book",
    "statusType": {
      "id": 1
    }
}