
### AUTH Login
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "kohado@aros.com",
  "password": "123456"
}

### create status content type
POST http://localhost:3000/status-contentype
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "name": [
    "lendo",
    "lido",
    "abandonado"
  ]
}

### create content type
POST http://localhost:3000/contenttype
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "name":"manga",
    "statusType": {
      "id": 2
    }
}

### GET all content type
GET http://localhost:3000/contenttype
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "name":"book",
    "statusType": {
      "id": 1
    }
}

### create content
POST http://localhost:3000/content
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: application/json

{
    "title":"Percy Jackson o ultimo olimpiano",
    "numberPages": 100,
    "isbn": "11245454",
    "description":"new book",
    "type": {
        "id": 8
    }

}

### get all content
GET http://localhost:3000/content/all

### update one content
PATCH http://localhost:3000/content/1
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: application/json

{
    "title":"Percy Jackson e o ladrão de raios"
}
